package Jira.RestAPIs;

import java.io.IOException;

import org.testng.annotations.Test;
import static io.restassured.RestAssured.*;
import io.restassured.RestAssured;
import io.restassured.path.json.JsonPath;
import utilities.baseclass;

public class a_Auth_and_Create_issue {
@Test
public void test1() throws IOException {
	RestAssured.baseURI = baseclass.getProperty("baseurl");
	//Authentication
	String resp = given().log().all().header("Content-Type","application/json").body("{ \"username\": \"lavesh\", \"password\": \"1234\" }").
	when().post("rest/auth/1/session").
	then().log().all().assertThat().statusCode(200).extract().response().asString();
	
	JsonPath js = baseclass.RawtoJSON(resp);
	String name = js.get("session.name");
	String id = js.get("session.value");
	
	System.out.println(name +" "+ id);
	
	//Creating defect
	String response = given().log().all().header("Content-Type","application/json").
			header("Cookie",name+"="+id).
	body("{\r\n"
			+ "  \"fields\": {\r\n"
			+ "    \"project\": {\r\n"
			+ "      \"key\": \"RES\"\r\n"
			+ "    },\r\n"
			+ "    \"summary\": \"Autogenerated defect\",\r\n"
			+ "    \"description\": \"This is a auto generated Bug\",\r\n"
			+ "    \"issuetype\": {\r\n"
			+ "      \"name\": \"Bug\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}").
	when().post("rest/api/2/issue").
	then().log().all().assertThat().statusCode(201).extract().response().asString();
	
	JsonPath js2 = baseclass.RawtoJSON(response);
	String sid = js2.getString("id");
	System.out.println(sid);
}
}
