package Jira.RestAPIs;

import static io.restassured.RestAssured.given;

import java.io.IOException;

import org.testng.annotations.Test;

import io.restassured.RestAssured;
import io.restassured.filter.session.SessionFilter;
import utilities.baseclass;

public class e_RelaxedHttpvalidation {
@Test
public void httpValidation() throws IOException {
	
	RestAssured.baseURI = baseclass.getProperty("baseurl");
	SessionFilter session = new SessionFilter();
	
	given().log().all().relaxedHTTPSValidation().header("Content-Type","application/json").filter(session)
	.body("{ \"username\": \"lavesh\", \"password\": \"1234\" }")
	.when().post("rest/auth/1/session")
	.then().log().all().assertThat().statusCode(200);
	
	String response = given().log().all().header("Content-Type","application/json").
			filter(session).
	body("{\r\n"
			+ "  \"fields\": {\r\n"
			+ "    \"project\": {\r\n"
			+ "      \"key\": \"RES\"\r\n"
			+ "    },\r\n"
			+ "    \"summary\": \"Autogenerated defect\",\r\n"
			+ "    \"description\": \"This is a auto generated Bug\",\r\n"
			+ "    \"issuetype\": {\r\n"
			+ "      \"name\": \"Bug\"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}").
	when().post("rest/api/2/issue").
	then().log().all().assertThat().statusCode(201).extract().response().asString();
	System.out.println(response);
	
}
}
